FROM node:12

RUN apt-get update && \
    apt-get install -y procps libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

USER root
RUN npm i -g --unsafe-perm=true --allow-root cypress@5.0.0
