/// <reference types="Cypress"/>

import { Given, When, Then } from 'cypress-cucumber-preprocessor/steps';

//Senario: REPORT V4 Spike Form and Financial Information
Given('already specific route to validate FI Report operation', () => {
    //Snippet - Report Identification
});

When('a GET request is executed correctly using spike form', () => {
    cy.request({
        method : 'GET',
        failOnStatusCode: false, url : 'https://turbo-api-dev.extremetest.io/v2/reports/rdi/881700385780?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHQiOiI0YWEwMGZlMTIwYmIyNDgwMDAwN2VhODQzOTY1MzE5NGEzYWJiOWIwYWYxZDFlZjViZWM3MTkzYTYwMzNmZTRiNzRmZGFmY2VmNDI3ZDA4M2JhNzFhN2VkNTc1ZjVhZmI2NGRmYTdjNTVmYjBlYzIwMjI2Mzc3OWY1ZDRjYzdmYTliMDM3ZDI5NzgyM2EwZGRjMDkxYzJlNjMzMDVkMzZiOTY4MGM1MzhmYTNjNzgyZDIyNzczZGRiZTc3ZTY3NmY0N2U1MDQ1MmFjZmIxZjcwN2Q3MzMzYjY5ODYxOTU4MWIwMjhjOTUyMTM4NGZiZTVjNWE4NzkwMGJhN2E4NWZkMmU4YTQwMmFmZTk2YmNjM2NmMjk5YTdlZDllZWIzOGE2NDI0YTliMGZiZjBhNWZiMmEwNzA0OWNkOWM3MmMyYjJkNjFkNDM5MWQ2ODUzMDA4NDYxMDMwMDZmMWUzNThjNmFmNWI5MDZmNjMwYmEyZjhhZWQ3OGRmNmJjNjdmNDExZDE1M2RkOTU5YWY4NTFiNDQwYWY4ZjNiYjQxMjI0MjIyMjRiZTA0MGJmNWNkZmMzYmI4ZGZlNDJlZjQ4OWJmYTcwYjVkMTE0N2VjYzc5MWQ4ZmMyNmVmYjBiYzExY2U3ZThlMDg0NGRjYjY2ODBiY2FmNDFlMTBlYzYzZTJkMTYxOWEzODk2YjNjNTAxZDA1NDAyMjYwNmZkODZmYTdlNzAzNDE4MDliYzQ2YmIxZDFhYjY3OGRhOTIxMmMyMzhlYjAzNWI1ODY1OTg3NDcxMDlkNTY0YTI5YjgzYTQ2YjM5NjU5ZjNmYTNjYjEzMTEyNjFmY2JiNjAyNWExYjkzMGMwZjRkYjI2NjI4NjExYWRkZWFhNjgzM2EwNmM5ZjJhNjc2OWJmMGU5ODQxMjFmNDVlYTc3ODQ3OTE3ZGUwMzU4NGE1YWZiNzUzNjk0NmIxNzg5YTM3ZGZiMTNkYmJhMGUzYjk5MjE3YTU2ZTA2NTJmNDE4Yjc2YmExZDdlNzk5YTBjYWY5Mjk0MjEyNGZhMzEzM2IyNTU0N2Y1M2UzNjhhNGJlOWEwNTIyMTU5ZWMwZGJmZDIxMjE3MzZkMzdjOTJmNmNhYTEzOWZmYmQwMDhlODE0OTRmZjc3NmMzMjI3ODliODFiMGIyY2JmODkxZDViYTE1MjRjZTJiODViYzJhZTFmZjBiMTU1ZDlhMDlkNTdjYzAzYWI5N2NiNGI2M2E5NzgzZmExZWFjNTBjNGE1NDU3MDFjYTJkN2EyZGE2OTc5MmZmZTRlNjNhNWMzYjVmZWZkY2RhZWFmNjNiODI5NDAwNzZlMGUyNDg3ZDg0MWVmOTk5YTJkZmZiNzk1MjBhMTI4MGVjNTU4ZGExMzg3Y2U0NGE1OTIwZTkzZmUxZTYwOWY4NWJjODUwOWIxZGYyYWIwNGZjYWNlOTZjNGM2YWRkYWU1OGNjMzAxYTg0Zjc1ZDI3MGM0OTE5ODk4NTkyNDU5ZDVmMmE2YTEwNzY2NzY3MThmYTkzYTRjZWU5MDJjN2IxNWU4N2RiZGU0Zjc4NDFkNzMyNTUxMWY0YmQzM2NlMDlhZjhlMzY0OTRkZTk0NDQ5YzRjOWEwZGVmODEyOWIwMTg3ZTdlZGZhYWQwYTk2NzkxOTJlZDMwYTQ0YTI4OTc3MTI5MzM0YTAyZmUxZDE5NjQzZDBiYmNmZmE0ZGU3MmVlOTcwZDc2ODNjNDU2NWUwYThkMzIzMTk4NmYwODQ1MzJjYmViYjM5ZmJkYThmYzQ3OTQ5YmQxNzNhN2RjOGVlMmQ0MmViOTg1MmNmNDkyYTFjZGJjZjBkZTRkMjUwYzViMjU3NyIsImlhdCI6MTYxMTA3NzYzMn0.NKZXvuufkBUuXyrWQ3DTC15olwlPtXCu8JIIUOgLdHo',
        auth: {
           bearer: '',
       },
    }).as('reportv4r1')
});

Then('the API will return a financial message successfully', (int) => {
    cy.get('@reportv4r1').should((response) => {
        var jsonData = JSON.stringify(response.body)
        expect(jsonData).to.have.string('document.FinancialSpikeCount()');
    })
});

//Senario: REPORT V4 Ragnar Form and Contact Information
Given('already specific route to validate CI report operation', () => {
    //Snippet - Report Identification
});

When('a GET request is executed correctly using ragnar form', () => {
    cy.request({
        method : 'GET',
        failOnStatusCode: false, url : 'https://turbo-api-dev.extremetest.io/v2/reports/rdi/890400667881?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHQiOiIxNDYwNjhmY2RiYjM5NzkxYzgwZTAxYjdjYjk2MzY3Y2M0ODhmODk5YTU0ZDUyNDA0ZjY3NjQ1NjE5N2ZjNTMxNGQ2Zjc0YTI2ZTcwMTNhNGRlMjRmNzQ4YTBiMTgxMzM3NmI5YjY4ZTYxZDIxOTNhM2I4NWQyM2NhNDRjMTQxNTJlNGJhNWE1MmI4ODUxNGE5ZDQwYzZkNTM1ODZiYWQ5ODRkZjBhMmQ2NGRhZWM0MmY3MTg4Nzc1MTZiMjQ2MjgxN2EyMjJkYzFiNDAwMzcwYWE5NTE5ZmNjMmVmOGNhN2VlMTg2ZjFjNWE0MjJlOGIyMjE1MzI3M2JhZTY5ZTIyZjcwZWM3OWZlMDcxMWRhMGJjYTRlZGQ4MDQ4NWI3N2JlYjgyZWJiZGYzMDZhMjVlMjU2ZjVhODYwYjI1MGQ4NWExNGM4NGRjOWNlZGJlZWM2YzRmZjkxYzlmNTRlYzA1M2VlN2E0MmU4MjdkNWNiM2UzZDA5OTFkOTNlM2I1OGQ3YjFhN2ZiOTA1ZmY3NTUxODhiNzM1ZWIxZGU4Njc4NjJjMDFkNDBkZGZjMGQ4YTM1NTM4ZGFiY2ExNTkxOGE3ZTM1YWNmYWUxNzYxZGEyY2E0MTUxMjU5MjQ4NmJhNDUzMzFmOThhZTllYzg2YjhjOGIyZTJkODY1OGZlMmZiOTI1YWI0YjQzNDA1ZDQzNmYwZDY3Y2NjNGUyNGM1MmI1ODVkZGY0MmMxMTAxZTkxMjBiZDRiMmEyODU4ZDM1OWZjNjI4MjNiYTdiNWI3MGYyMzU2ZTI4NGFhMmE0Njg1ZDBjNTM1NThlYzJjYmQ5OWZiMzI0NWE3YzY4MTZkN2E2YzhkMjdjMzhhNjdlMTZmODM0YWExZWE3MjBmNDQ3OWIzOGE2MzBhNDJiYjU3ZDBmN2FlMmQ1OTQ2NDAzYjU2Yjk3MWI0MmEzOWY5OWIyYTU0YjUyMDViMGU3MmZjMDRkYTc0MjMxY2UzZTZjNWNhYmU1YTE5MjFiYjFjZTRiYzdhYjJjYmFiZjRjZmUwNmViNTQ2MDA4OTBlN2Q5MTYwNjdhMDc4ODViMGZlOTJjMGUwODc4MmYyZmQ5YWQyM2EyYjE4Y2EwNjE1NWVkMzRlZTg2NDA5MDA3OTE3MzAyMTM3NTllMjQ5ODA5NWUxODQ3YWI0MGEyOTU5YTIwMDAyMzYxNTAzOTUzZjVkZTc5ODI4Zjc1YTM5ODA2NGU4NDk3NWI0OTM4ZWEyYjk5MDA0YjlmMDU2MWVmZDdmZTVkMDRlNTFmMDMxYWY1NGRhYmIwYmM5MThiMTk2YzEwOWE1MTVjNTVjY2E0NTIwMjFjOTQzMjcxYjdmZmYzZWExZWY1NmZkYjYzYTI4OWZjNDA5OWRiNDMwMmU0YTRkZDJkZjQ5MWEzNGMwZjNhZTJmOTZiNzJjZmEyYzIxNGQ0Y2VlZmI5ZmRkNTQzMWNkN2JmNzRjMGU0YzZmMjM4ZjIxNGZmZGMxYjFiY2E5YmYzM2YxZjIzIiwiaWF0IjoxNjE1NDE1MDk1fQ.abqU5kPkO5MQZSTRNuuRbt-wlXHsY2cojJ7E8VVSFVk',
        auth: {
           bearer: '',
       },
    }).as('reportv4r2')
});

Then('the API will return a contact message correctly', (int) => {
    cy.get('@reportv4r2').should((response) => {
        var jsonData = JSON.stringify(response.body)
        expect(jsonData).to.have.string('document.RagnarID.Name.Phone.Count()');
    })
});